package diceprogram;


import diceprogram.Player;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 22013691
 */
public class DiceGame extends javax.swing.JFrame {

    /**
     * Creates new form DiceGame
     */
    
    Player[] thePlayers = new Player[2];
    
    public DiceGame() {
        initComponents();
         for (int i = 0; i < thePlayers.length; i++) {
            thePlayers[i] = new Player();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_welcome = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        lbl_welcomeMessage = new javax.swing.JLabel();
        pnl_userData = new javax.swing.JPanel();
        txt_player0Name = new javax.swing.JTextField();
        txt_player1Name = new javax.swing.JTextField();
        lbl_player0 = new javax.swing.JLabel();
        lbl_player1 = new javax.swing.JLabel();
        btn_play = new javax.swing.JButton();
        pnl_game = new javax.swing.JPanel();
        lbl_player0Name = new javax.swing.JLabel();
        lbl_player1Name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_player0Output = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_player1Output = new javax.swing.JTextArea();
        btn_roll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        btn_start.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btn_start.setText("START");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        lbl_welcomeMessage.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lbl_welcomeMessage.setText("Welcome to the Dice Game");

        javax.swing.GroupLayout pnl_welcomeLayout = new javax.swing.GroupLayout(pnl_welcome);
        pnl_welcome.setLayout(pnl_welcomeLayout);
        pnl_welcomeLayout.setHorizontalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_welcomeLayout.createSequentialGroup()
                        .addComponent(btn_start)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_welcomeLayout.createSequentialGroup()
                        .addComponent(lbl_welcomeMessage)
                        .addGap(90, 90, 90))))
        );
        pnl_welcomeLayout.setVerticalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_welcomeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbl_welcomeMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btn_start)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnl_welcome, "card2");

        lbl_player0.setText("Player 1:");

        lbl_player1.setText("Player2:");

        btn_play.setText("PLAY");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_userDataLayout = new javax.swing.GroupLayout(pnl_userData);
        pnl_userData.setLayout(pnl_userDataLayout);
        pnl_userDataLayout.setHorizontalGroup(
            pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userDataLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_player1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_player0, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_play)
                    .addComponent(txt_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        pnl_userDataLayout.setVerticalGroup(
            pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userDataLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_player0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_userDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_player1))
                .addGap(65, 65, 65)
                .addComponent(btn_play)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_userData, "card3");

        lbl_player0Name.setText("jLabel1");

        lbl_player1Name.setText("jLabel2");

        txt_player0Output.setColumns(20);
        txt_player0Output.setRows(5);
        jScrollPane1.setViewportView(txt_player0Output);

        txt_player1Output.setColumns(20);
        txt_player1Output.setRows(5);
        jScrollPane2.setViewportView(txt_player1Output);

        btn_roll.setText("ROLL");
        btn_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_gameLayout = new javax.swing.GroupLayout(pnl_game);
        pnl_game.setLayout(pnl_gameLayout);
        pnl_gameLayout.setHorizontalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lbl_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btn_roll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_gameLayout.setVerticalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_player0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btn_roll)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_game, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        pnl_welcome.setVisible(false);
        pnl_userData.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        pnl_userData.setVisible(false);
        pnl_game.setVisible(true);
        
        thePlayers[0].setPlayerName(txt_player0Name.getText());
        thePlayers[1].setPlayerName(txt_player1Name.getText());
        
        lbl_player0Name.setText(thePlayers[0].getPlayerName());
        lbl_player1Name.setText(thePlayers[1].getPlayerName());
        
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollActionPerformed
        // TODO add your handling code here:
        txt_player0Output.append(thePlayers[0].getPlayerName() + " rolled a " + thePlayers[0].getPlayerDice(0).rollDice() + " and a " + thePlayers[0].getPlayerDice(1).rollDice() + "\n");
        txt_player1Output.append(thePlayers[1].getPlayerName() + " rolled a " + thePlayers[1].getPlayerDice(0).rollDice() + " and a " + thePlayers[1].getPlayerDice(1).rollDice()+ "\n");
        
        if (thePlayers[0].getPlayerDice(0).getCurrentShownFace() == thePlayers[0].getPlayerDice(1).getCurrentShownFace()){
            thePlayers[0].setHasWon(true);
        } 
            
        if (thePlayers[1].getPlayerDice(0).getCurrentShownFace() == thePlayers[1].getPlayerDice(1).getCurrentShownFace()){
            thePlayers[1].setHasWon(true);
        }
        
        if (thePlayers[0].isHasWon() && thePlayers[1].isHasWon())
            JOptionPane.showMessageDialog(null, "It was a draw!");
        else if (thePlayers[0].isHasWon())
            JOptionPane.showMessageDialog(null, thePlayers[0].getPlayerName() + " has won!!");
        else if (thePlayers[1].isHasWon())
            JOptionPane.showMessageDialog(null, thePlayers[1].getPlayerName() + " has won!!");
    }//GEN-LAST:event_btn_rollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_roll;
    private javax.swing.JButton btn_start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_player0;
    private javax.swing.JLabel lbl_player0Name;
    private javax.swing.JLabel lbl_player1;
    private javax.swing.JLabel lbl_player1Name;
    private javax.swing.JLabel lbl_welcomeMessage;
    private javax.swing.JPanel pnl_game;
    private javax.swing.JPanel pnl_userData;
    private javax.swing.JPanel pnl_welcome;
    private javax.swing.JTextField txt_player0Name;
    private javax.swing.JTextArea txt_player0Output;
    private javax.swing.JTextField txt_player1Name;
    private javax.swing.JTextArea txt_player1Output;
    // End of variables declaration//GEN-END:variables
}
